name: Automatically convert readme.md to readme.txt using pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: |
          echo "::set-output name=files::$(printf '"%s" ' readme.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=./readme.txt ${{ steps.files_list.outputs.files }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: .
